<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_zotero_feeds_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "feeds" && $api == 'feeds_importer_default') {
    return array("version" => 1);
  }
}

/**
 * Implements of hook_feeds_plugins().
 */
function feeds_zotero_feeds_plugins() {
  $info = array();

  $info['FeedsZoteroHTTPFetcher'] = array(
    'name' => 'Zotero HTTP Fetcher',
    'description' => 'Fetches user and group libraries from Zotero.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher',
      'class' => 'FeedsZoteroHTTPFetcher',
      'file' => 'FeedsZoteroHTTPFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_zotero'),
    ),
  );

  return $info;
}
